services:
  # default configuration for services in *this* file
  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true
    # this means you cannot fetch services directly from the container via $container->get()
    # if you need to do this, you can override this setting on individual services
    public: false

  OpenSwooleServerBundle\Swoole\Server:
    public: true
    arguments: [ "", "", "", "", "@kernel", "@logger", null, true, null, null ]

  OpenSwooleServerBundle\Command\:
    resource: '../../Command'
    tags:
      - console.command

  OpenSwooleServerBundle\EventSubscriber\ContainerSubscriber:
    class: OpenSwooleServerBundle\EventSubscriber\ContainerSubscriber
    arguments:
      - !tagged_iterator kernel.reset
    tags:
      - { name: kernel.event_subscriber }

  OpenSwooleServerBundle\EventSubscriber\AMQPReconnectSubscriber:
    public: true
    class: OpenSwooleServerBundle\EventSubscriber\AMQPReconnectSubscriber
    tags:
      - { name: kernel.event_subscriber }
  
  openswoole_server_bundle.server_task_handler:
    class: OpenSwooleServerBundle\Swoole\Handler\MessengerSendTaskHandler
  
  openswoole_server_bundle.server_task_finish_handler:
    class: OpenSwooleServerBundle\Swoole\Handler\NoopTaskFinishHandler

  OpenSwooleServerBundle\Swoole\Handler\TaskHandlerInterface:
    alias: openswoole_server_bundle.server_task_handler
    public: true

  OpenSwooleServerBundle\Swoole\Handler\TaskFinishHandlerInterface:
    alias: openswoole_server_bundle.server_task_finish_handler
    public: true
